import { TubeLine, Station, Session } from './types';

export const TUBE_LINE_COLORS: Record<TubeLine, string> = {
  [TubeLine.BAKERLOO]: '#B36305',
  [TubeLine.CENTRAL]: '#E32017',
  [TubeLine.CIRCLE]: '#FFD300',
  [TubeLine.DISTRICT]: '#00782A',
  [TubeLine.HAMMERSMITH_CITY]: '#F3A9BB',
  [TubeLine.JUBILEE]: '#A0A5A9',
  [TubeLine.METROPOLITAN]: '#9B0056',
  [TubeLine.NORTHERN]: '#000000',
  [TubeLine.PICCADILLY]: '#003688',
  [TubeLine.VICTORIA]: '#0098D4',
  [TubeLine.WATERLOO_CITY]: '#95CDBA',
  [TubeLine.DLR]: '#00A4A7',
  [TubeLine.OVERGROUND]: '#EE7C0E',
  [TubeLine.ELIZABETH]: '#6950a1',
};

export const STATIONS: Station[] = [
    { id: 'acton-town', name: 'Acton Town', line: TubeLine.DISTRICT },
    { id: 'aldgate', name: 'Aldgate', line: TubeLine.CIRCLE },
    { id: 'aldgate-east', name: 'Aldgate East', line: TubeLine.DISTRICT },
    { id: 'alperton', name: 'Alperton', line: TubeLine.PICCADILLY },
    { id: 'angel', name: 'Angel', line: TubeLine.NORTHERN },
    { id: 'archway', name: 'Archway', line: TubeLine.NORTHERN },
    { id: 'arnos-grove', name: 'Arnos Grove', line: TubeLine.PICCADILLY },
    { id: 'arsenal', name: 'Arsenal', line: TubeLine.PICCADILLY },
    { id: 'baker-street', name: 'Baker Street', line: TubeLine.BAKERLOO },
    { id: 'balham', name: 'Balham', line: TubeLine.NORTHERN },
    { id: 'bank', name: 'Bank', line: TubeLine.CENTRAL },
    { id: 'barbican', name: 'Barbican', line: TubeLine.CIRCLE },
    { id: 'barking', name: 'Barking', line: TubeLine.DISTRICT },
    { id: 'bayswater', name: 'Bayswater', line: TubeLine.CIRCLE },
    { id: 'belsize-park', name: 'Belsize Park', line: TubeLine.NORTHERN },
    { id: 'bermondsey', name: 'Bermondsey', line: TubeLine.JUBILEE },
    { id: 'bethnal-green', name: 'Bethnal Green', line: TubeLine.CENTRAL },
    { id: 'blackfriars', name: 'Blackfriars', line: TubeLine.CIRCLE },
    { id: 'bond-street', name: 'Bond Street', line: TubeLine.CENTRAL },
    { id: 'borough', name: 'Borough', line: TubeLine.NORTHERN },
    { id: 'boston-manor', name: 'Boston Manor', line: TubeLine.PICCADILLY },
    { id: 'bounds-green', name: 'Bounds Green', line: TubeLine.PICCADILLY },
    { id: 'bow-road', name: 'Bow Road', line: TubeLine.DISTRICT },
    { id: 'brent-cross', name: 'Brent Cross', line: TubeLine.NORTHERN },
    { id: 'brixton', name: 'Brixton', line: TubeLine.VICTORIA },
    { id: 'buckhurst-hill', name: 'Buckhurst Hill', line: TubeLine.CENTRAL },
    { id: 'burnt-oak', name: 'Burnt Oak', line: TubeLine.NORTHERN },
    { id: 'caledonian-road', name: 'Caledonian Road', line: TubeLine.PICCADILLY },
    { id: 'camden-town', name: 'Camden Town', line: TubeLine.NORTHERN },
    { id: 'canada-water', name: 'Canada Water', line: TubeLine.JUBILEE },
    { id: 'canary-wharf', name: 'Canary Wharf', line: TubeLine.JUBILEE },
    { id: 'canning-town', name: 'Canning Town', line: TubeLine.JUBILEE },
    { id: 'cannon-street', name: 'Cannon Street', line: TubeLine.CIRCLE },
    { id: 'chalfont-latimer', name: 'Chalfont & Latimer', line: TubeLine.METROPOLITAN },
    { id: 'chalk-farm', name: 'Chalk Farm', line: TubeLine.NORTHERN },
    { id: 'chancery-lane', name: 'Chancery Lane', line: TubeLine.CENTRAL },
    { id: 'charing-cross', name: 'Charing Cross', line: TubeLine.BAKERLOO },
    { id: 'chesham', name: 'Chesham', line: TubeLine.METROPOLITAN },
    { id: 'chorleywood', name: 'Chorleywood', line: TubeLine.METROPOLITAN },
    { id: 'clapham-common', name: 'Clapham Common', line: TubeLine.NORTHERN },
    { id: 'clapham-north', name: 'Clapham North', line: TubeLine.NORTHERN },
    { id: 'clapham-south', name: 'Clapham South', line: TubeLine.NORTHERN },
    { id: 'cockfosters', name: 'Cockfosters', line: TubeLine.PICCADILLY },
    { id: 'colindale', name: 'Colindale', line: TubeLine.NORTHERN },
    { id: 'colliers-wood', name: 'Colliers Wood', line: TubeLine.NORTHERN },
    { id: 'covent-garden', name: 'Covent Garden', line: TubeLine.PICCADILLY },
    { id: 'croxley', name: 'Croxley', line: TubeLine.METROPOLITAN },
    { id: 'dagenham-east', name: 'Dagenham East', line: TubeLine.DISTRICT },
    { id: 'dagenham-heathway', name: 'Dagenham Heathway', line: TubeLine.DISTRICT },
    { id: 'debden', name: 'Debden', line: TubeLine.CENTRAL },
    { id: 'dollis-hill', name: 'Dollis Hill', line: TubeLine.JUBILEE },
    { id: 'ealing-broadway', name: 'Ealing Broadway', line: TubeLine.CENTRAL },
    { id: 'ealing-common', name: 'Ealing Common', line: TubeLine.DISTRICT },
    { id: 'earls-court', name: 'Earl\'s Court', line: TubeLine.DISTRICT },
    { id: 'east-acton', name: 'East Acton', line: TubeLine.CENTRAL },
    { id: 'east-finchley', name: 'East Finchley', line: TubeLine.NORTHERN },
    { id: 'east-ham', name: 'East Ham', line: TubeLine.DISTRICT },
    { id: 'east-putney', name: 'East Putney', line: TubeLine.DISTRICT },
    { id: 'eastcote', name: 'Eastcote', line: TubeLine.PICCADILLY },
    { id: 'edgware', name: 'Edgware', line: TubeLine.NORTHERN },
    { id: 'edgware-road-bakerloo', name: 'Edgware Road', line: TubeLine.BAKERLOO },
    { id: 'edgware-road-circle', name: 'Edgware Road', line: TubeLine.CIRCLE },
    { id: 'elephant-castle', name: 'Elephant & Castle', line: TubeLine.BAKERLOO },
    { id: 'elm-park', name: 'Elm Park', line: TubeLine.DISTRICT },
    { id: 'embankment', name: 'Embankment', line: TubeLine.BAKERLOO },
    { id: 'epping', name: 'Epping', line: TubeLine.CENTRAL },
    { id: 'euston', name: 'Euston', line: TubeLine.VICTORIA },
    { id: 'euston-square', name: 'Euston Square', line: TubeLine.CIRCLE },
    { id: 'fairlop', name: 'Fairlop', line: TubeLine.CENTRAL },
    { id: 'farringdon', name: 'Farringdon', line: TubeLine.ELIZABETH },
    { id: 'finchley-central', name: 'Finchley Central', line: TubeLine.NORTHERN },
    { id: 'finchley-road', name: 'Finchley Road', line: TubeLine.JUBILEE },
    { id: 'finsbury-park', name: 'Finsbury Park', line: TubeLine.PICCADILLY },
    { id: 'fulham-broadway', name: 'Fulham Broadway', line: TubeLine.DISTRICT },
    { id: 'gants-hill', name: 'Gants Hill', line: TubeLine.CENTRAL },
    { id: 'gloucester-road', name: 'Gloucester Road', line: TubeLine.CIRCLE },
    { id: 'golders-green', name: 'Golders Green', line: TubeLine.NORTHERN },
    { id: 'goodge-street', name: 'Goodge Street', line: TubeLine.NORTHERN },
    { id: 'great-portland-street', name: 'Great Portland Street', line: TubeLine.CIRCLE },
    { id: 'green-park', name: 'Green Park', line: TubeLine.JUBILEE },
    { id: 'greenford', name: 'Greenford', line: TubeLine.CENTRAL },
    { id: 'gunnersbury', name: 'Gunnersbury', line: TubeLine.DISTRICT },
    { id: 'hainault', name: 'Hainault', line: TubeLine.CENTRAL },
    { id: 'hammersmith', name: 'Hammersmith', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'hampstead', name: 'Hampstead', line: TubeLine.NORTHERN },
    { id: 'hanger-lane', name: 'Hanger Lane', line: TubeLine.CENTRAL },
    { id: 'harlesden', name: 'Harlesden', line: TubeLine.BAKERLOO },
    { id: 'harrow-weald', name: 'Harrow & Wealdstone', line: TubeLine.BAKERLOO },
    { id: 'harrow-on-the-hill', name: 'Harrow-on-the-Hill', line: TubeLine.METROPOLITAN },
    { id: 'hatton-cross', name: 'Hatton Cross', line: TubeLine.PICCADILLY },
    { id: 'heathrow-123', name: 'Heathrow Terminals 1, 2, 3', line: TubeLine.PICCADILLY },
    { id: 'heathrow-4', name: 'Heathrow Terminal 4', line: TubeLine.PICCADILLY },
    { id: 'heathrow-5', name: 'Heathrow Terminal 5', line: TubeLine.PICCADILLY },
    { id: 'hendon-central', name: 'Hendon Central', line: TubeLine.NORTHERN },
    { id: 'high-barnet', name: 'High Barnet', line: TubeLine.NORTHERN },
    { id: 'high-street-kensington', name: 'High Street Kensington', line: TubeLine.CIRCLE },
    { id: 'highbury-islington', name: 'Highbury & Islington', line: TubeLine.VICTORIA },
    { id: 'highgate', name: 'Highgate', line: TubeLine.NORTHERN },
    { id: 'hillingdon', name: 'Hillingdon', line: TubeLine.PICCADILLY },
    { id: 'holborn', name: 'Holborn', line: TubeLine.CENTRAL },
    { id: 'holland-park', name: 'Holland Park', line: TubeLine.CENTRAL },
    { id: 'holloway-road', name: 'Holloway Road', line: TubeLine.PICCADILLY },
    { id: 'hornchurch', name: 'Hornchurch', line: TubeLine.DISTRICT },
    { id: 'hounslow-central', name: 'Hounslow Central', line: TubeLine.PICCADILLY },
    { id: 'hounslow-east', name: 'Hounslow East', line: TubeLine.PICCADILLY },
    { id: 'hounslow-west', name: 'Hounslow West', line: TubeLine.PICCADILLY },
    { id: 'hyde-park-corner', name: 'Hyde Park Corner', line: TubeLine.PICCADILLY },
    { id: 'ickenham', name: 'Ickenham', line: TubeLine.PICCADILLY },
    { id: 'kennington', name: 'Kennington', line: TubeLine.NORTHERN },
    { id: 'kensal-green', name: 'Kensal Green', line: TubeLine.BAKERLOO },
    { id: 'kensington-olympia', name: 'Kensington (Olympia)', line: TubeLine.DISTRICT },
    { id: 'kentish-town', name: 'Kentish Town', line: TubeLine.NORTHERN },
    { id: 'kew-gardens', name: 'Kew Gardens', line: TubeLine.DISTRICT },
    { id: 'kilburn', name: 'Kilburn', line: TubeLine.JUBILEE },
    { id: 'kilburn-park', name: 'Kilburn Park', line: TubeLine.BAKERLOO },
    { id: 'king-cross-st-pancras', name: 'King\'s Cross St. Pancras', line: TubeLine.PICCADILLY },
    { id: 'kingsbury', name: 'Kingsbury', line: TubeLine.JUBILEE },
    { id: 'knightsbridge', name: 'Knightsbridge', line: TubeLine.PICCADILLY },
    { id: 'ladbroke-grove', name: 'Ladbroke Grove', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'lambeth-north', name: 'Lambeth North', line: TubeLine.BAKERLOO },
    { id: 'lancaster-gate', name: 'Lancaster Gate', line: TubeLine.CENTRAL },
    { id: 'latimer-road', name: 'Latimer Road', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'leicester-square', name: 'Leicester Square', line: TubeLine.NORTHERN },
    { id: 'leyton', name: 'Leyton', line: TubeLine.CENTRAL },
    { id: 'leytonstone', name: 'Leytonstone', line: TubeLine.CENTRAL },
    { id: 'liverpool-street', name: 'Liverpool Street', line: TubeLine.CENTRAL },
    { id: 'london-bridge', name: 'London Bridge', line: TubeLine.JUBILEE },
    { id: 'loughton', name: 'Loughton', line: TubeLine.CENTRAL },
    { id: 'maida-vale', name: 'Maida Vale', line: TubeLine.BAKERLOO },
    { id: 'manor-house', name: 'Manor House', line: TubeLine.PICCADILLY },
    { id: 'mansion-house', name: 'Mansion House', line: TubeLine.CIRCLE },
    { id: 'marble-arch', name: 'Marble Arch', line: TubeLine.CENTRAL },
    { id: 'marylebone', name: 'Marylebone', line: TubeLine.BAKERLOO },
    { id: 'mile-end', name: 'Mile End', line: TubeLine.CENTRAL },
    { id: 'mill-hill-east', name: 'Mill Hill East', line: TubeLine.NORTHERN },
    { id: 'monument', name: 'Monument', line: TubeLine.CIRCLE },
    { id: 'moor-park', name: 'Moor Park', line: TubeLine.METROPOLITAN },
    { id: 'moorgate', name: 'Moorgate', line: TubeLine.CIRCLE },
    { id: 'morden', name: 'Morden', line: TubeLine.NORTHERN },
    { id: 'mornington-crescent', name: 'Mornington Crescent', line: TubeLine.NORTHERN },
    { id: 'neasden', name: 'Neasden', line: TubeLine.JUBILEE },
    { id: 'newbury-park', name: 'Newbury Park', line: TubeLine.CENTRAL },
    { id: 'north-acton', name: 'North Acton', line: TubeLine.CENTRAL },
    { id: 'north-ealing', name: 'North Ealing', line: TubeLine.PICCADILLY },
    { id: 'north-greenwich', name: 'North Greenwich', line: TubeLine.JUBILEE },
    { id: 'north-harrow', name: 'North Harrow', line: TubeLine.METROPOLITAN },
    { id: 'north-wembley', name: 'North Wembley', line: TubeLine.BAKERLOO },
    { id: 'northfields', name: 'Northfields', line: TubeLine.PICCADILLY },
    { id: 'northolt', name: 'Northolt', line: TubeLine.CENTRAL },
    { id: 'northwick-park', name: 'Northwick Park', line: TubeLine.METROPOLITAN },
    { id: 'northwood', name: 'Northwood', line: TubeLine.METROPOLITAN },
    { id: 'northwood-hills', name: 'Northwood Hills', line: TubeLine.METROPOLITAN },
    { id: 'notting-hill-gate', name: 'Notting Hill Gate', line: TubeLine.CENTRAL },
    { id: 'oakwood', name: 'Oakwood', line: TubeLine.PICCADILLY },
    { id: 'old-street', name: 'Old Street', line: TubeLine.NORTHERN },
    { id: 'osterley', name: 'Osterley', line: TubeLine.PICCADILLY },
    { id: 'oval', name: 'Oval', line: TubeLine.NORTHERN },
    { id: 'oxford-circus', name: 'Oxford Circus', line: TubeLine.CENTRAL },
    { id: 'paddington', name: 'Paddington', line: TubeLine.BAKERLOO },
    { id: 'park-royal', name: 'Park Royal', line: TubeLine.PICCADILLY },
    { id: 'parsons-green', name: 'Parsons Green', line: TubeLine.DISTRICT },
    { id: 'perivale', name: 'Perivale', line: TubeLine.CENTRAL },
    { id: 'piccadilly-circus', name: 'Piccadilly Circus', line: TubeLine.BAKERLOO },
    { id: 'pimlico', name: 'Pimlico', line: TubeLine.VICTORIA },
    { id: 'pinner', name: 'Pinner', line: TubeLine.METROPOLITAN },
    { id: 'plaistow', name: 'Plaistow', line: TubeLine.DISTRICT },
    { id: 'preston-road', name: 'Preston Road', line: TubeLine.METROPOLITAN },
    { id: 'putney-bridge', name: 'Putney Bridge', line: TubeLine.DISTRICT },
    { id: 'queens-park', name: 'Queen\'s Park', line: TubeLine.BAKERLOO },
    { id: 'queensbury', name: 'Queensbury', line: TubeLine.JUBILEE },
    { id: 'queensway', name: 'Queensway', line: TubeLine.CENTRAL },
    { id: 'ravenscourt-park', name: 'Ravenscourt Park', line: TubeLine.DISTRICT },
    { id: 'rayners-lane', name: 'Rayners Lane', line: TubeLine.PICCADILLY },
    { id: 'redbridge', name: 'Redbridge', line: TubeLine.CENTRAL },
    { id: 'regent-park', name: 'Regent\'s Park', line: TubeLine.BAKERLOO },
    { id: 'richmond', name: 'Richmond', line: TubeLine.DISTRICT },
    { id: 'rickmansworth', name: 'Rickmansworth', line: TubeLine.METROPOLITAN },
    { id: 'roding-valley', name: 'Roding Valley', line: TubeLine.CENTRAL },
    { id: 'royal-oak', name: 'Royal Oak', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'ruislip', name: 'Ruislip', line: TubeLine.PICCADILLY },
    { id: 'ruislip-gardens', name: 'Ruislip Gardens', line: TubeLine.CENTRAL },
    { id: 'ruislip-manor', name: 'Ruislip Manor', line: TubeLine.PICCADILLY },
    { id: 'russell-square', name: 'Russell Square', line: TubeLine.PICCADILLY },
    { id: 'seven-sisters', name: 'Seven Sisters', line: TubeLine.VICTORIA },
    { id: 'shepherd-bush-central', name: 'Shepherd\'s Bush', line: TubeLine.CENTRAL },
    { id: 'shepherd-bush-hammersmith', name: 'Shepherd\'s Bush Market', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'sloane-square', name: 'Sloane Square', line: TubeLine.CIRCLE },
    { id: 'snaresbrook', name: 'Snaresbrook', line: TubeLine.CENTRAL },
    { id: 'south-ealing', name: 'South Ealing', line: TubeLine.PICCADILLY },
    { id: 'south-harrow', name: 'South Harrow', line: TubeLine.PICCADILLY },
    { id: 'south-kensington', name: 'South Kensington', line: TubeLine.CIRCLE },
    { id: 'south-kenton', name: 'South Kenton', line: TubeLine.BAKERLOO },
    { id: 'south-ruislip', name: 'South Ruislip', line: TubeLine.CENTRAL },
    { id: 'south-wimbledon', name: 'South Wimbledon', line: TubeLine.NORTHERN },
    { id: 'south-woodford', name: 'South Woodford', line: TubeLine.CENTRAL },
    { id: 'southfields', name: 'Southfields', line: TubeLine.DISTRICT },
    { id: 'southgate', name: 'Southgate', line: TubeLine.PICCADILLY },
    { id: 'southwark', name: 'Southwark', line: TubeLine.JUBILEE },
    { id: 'stamford-brook', name: 'Stamford Brook', line: TubeLine.DISTRICT },
    { id: 'stanmore', name: 'Stanmore', line: TubeLine.JUBILEE },
    { id: 'stepney-green', name: 'Stepney Green', line: TubeLine.DISTRICT },
    { id: 'stockwell', name: 'Stockwell', line: TubeLine.NORTHERN },
    { id: 'stonebridge-park', name: 'Stonebridge Park', line: TubeLine.BAKERLOO },
    { id: 'stratford', name: 'Stratford', line: TubeLine.CENTRAL },
    { id: 'st-james-park', name: 'St. James\'s Park', line: TubeLine.CIRCLE },
    { id: 'st-johns-wood', name: 'St. John\'s Wood', line: TubeLine.JUBILEE },
    { id: 'st-pauls', name: 'St. Paul\'s', line: TubeLine.CENTRAL },
    { id: 'sudbury-hill', name: 'Sudbury Hill', line: TubeLine.PICCADILLY },
    { id: 'sudbury-town', name: 'Sudbury Town', line: TubeLine.PICCADILLY },
    { id: 'swiss-cottage', name: 'Swiss Cottage', line: TubeLine.JUBILEE },
    { id: 'temple', name: 'Temple', line: TubeLine.CIRCLE },
    { id: 'theydon-bois', name: 'Theydon Bois', line: TubeLine.CENTRAL },
    { id: 'tooting-bec', name: 'Tooting Bec', line: TubeLine.NORTHERN },
    { id: 'tooting-broadway', name: 'Tooting Broadway', line: TubeLine.NORTHERN },
    { id: 'tottenham-court-road', name: 'Tottenham Court Road', line: TubeLine.CENTRAL },
    { id: 'tottenham-hale', name: 'Tottenham Hale', line: TubeLine.VICTORIA },
    { id: 'totteridge-whetstone', name: 'Totteridge & Whetstone', line: TubeLine.NORTHERN },
    { id: 'tower-hill', name: 'Tower Hill', line: TubeLine.CIRCLE },
    { id: 'tufnell-park', name: 'Tufnell Park', line: TubeLine.NORTHERN },
    { id: 'turnham-green', name: 'Turnham Green', line: TubeLine.DISTRICT },
    { id: 'turnpike-lane', name: 'Turnpike Lane', line: TubeLine.PICCADILLY },
    { id: 'upminster', name: 'Upminster', line: TubeLine.DISTRICT },
    { id: 'upminster-bridge', name: 'Upminster Bridge', line: TubeLine.DISTRICT },
    { id: 'upney', name: 'Upney', line: TubeLine.DISTRICT },
    { id: 'upton-park', name: 'Upton Park', line: TubeLine.DISTRICT },
    { id: 'uxbridge', name: 'Uxbridge', line: TubeLine.PICCADILLY },
    { id: 'vauxhall', name: 'Vauxhall', line: TubeLine.VICTORIA },
    { id: 'victoria', name: 'Victoria', line: TubeLine.VICTORIA },
    { id: 'walthamstow-central', name: 'Walthamstow Central', line: TubeLine.VICTORIA },
    { id: 'wandsworth-road', name: 'Wandsworth Road', line: TubeLine.NORTHERN },
    { id: 'warren-street', name: 'Warren Street', line: TubeLine.NORTHERN },
    { id: 'warwick-avenue', name: 'Warwick Avenue', line: TubeLine.BAKERLOO },
    { id: 'waterloo', name: 'Waterloo', line: TubeLine.BAKERLOO },
    { id: 'watford', name: 'Watford', line: TubeLine.METROPOLITAN },
    { id: 'wembley-central', name: 'Wembley Central', line: TubeLine.BAKERLOO },
    { id: 'wembley-park', name: 'Wembley Park', line: TubeLine.JUBILEE },
    { id: 'west-acton', name: 'West Acton', line: TubeLine.CENTRAL },
    { id: 'west-brompton', name: 'West Brompton', line: TubeLine.DISTRICT },
    { id: 'west-finchley', name: 'West Finchley', line: TubeLine.NORTHERN },
    { id: 'west-ham', name: 'West Ham', line: TubeLine.DISTRICT },
    { id: 'west-hampstead', name: 'West Hampstead', line: TubeLine.JUBILEE },
    { id: 'west-harrow', name: 'West Harrow', line: TubeLine.METROPOLITAN },
    { id: 'west-kensington', name: 'West Kensington', line: TubeLine.DISTRICT },
    { id: 'west-ruislip', name: 'West Ruislip', line: TubeLine.CENTRAL },
    { id: 'westbourne-park', name: 'Westbourne Park', line: TubeLine.HAMMERSMITH_CITY },
    { id: 'westminster', name: 'Westminster', line: TubeLine.CIRCLE },
    { id: 'whitechapel', name: 'Whitechapel', line: TubeLine.DISTRICT },
    { id: 'willesden-green', name: 'Willesden Green', line: TubeLine.JUBILEE },
    { id: 'willesden-junction', name: 'Willesden Junction', line: TubeLine.BAKERLOO },
    { id: 'wimbledon', name: 'Wimbledon', line: TubeLine.DISTRICT },
    { id: 'wimbledon-park', name: 'Wimbledon Park', line: TubeLine.DISTRICT },
    { id: 'wood-green', name: 'Wood Green', line: TubeLine.PICCADILLY },
    { id: 'woodford', name: 'Woodford', line: TubeLine.CENTRAL },
    { id: 'woodside-park', name: 'Woodside Park', line: TubeLine.NORTHERN },
].sort((a, b) => a.name.localeCompare(b.name));

export const SESSIONS: Session[] = [
    { id: 's1', time: '11:00 – 13:00', capacity: 25 },
    { id: 's2', time: '13:00 – 15:00', capacity: 25 },
    { id: 's3', time: '15:00 – 17:00', capacity: 25 },
    { id: 's4', time: '17:00 – 19:00', capacity: 25 },
    { id: 's5', time: '19:00 – 21:00', capacity: 25 },
];

export const FRIEND_GROUPS = [
    'KYUEM',
    'Taylors',
    'IBMers',
    'Lilly',
    'SSA',
    'SEB',
    'Surrey',
    'UCL',
    'KCL',
    'ICL',
    'Other',
];